import ThemeProvider from "@/components/Theme/ThemeProvider";
import "./globals.css";
import Aside from "@/components/Navigation/Aside";
import Header from "@/components/Navigation/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="min-h-screen bg-gray-50 dark:bg-gray-900 dark:text-white flex"
      >
        <ThemeProvider>
          <Header />
          <section className="flex flex-row mt-[80px]">
            <Aside />
            <main className="flex-1 p-4">{children}</main>
          </section>
        </ThemeProvider>
      </body>
    </html>
  );
}
